version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
      - echo "******** Uploading to S3 ********"
      - aws s3 sync build s3://cmp-pipeline-test/build_test 
artifacts:
  files:
    - broadleaf.json
  discard-paths: yes
