version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
artifacts:
  files:
    - ./src/github.com/daviseban/DemoSite/site/target/mycompany.war
  discard-paths: yes
