version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ https://s3.us-east-2.amazonaws.com/cmp-pipeline-test/build_test/
