version: 0.2
phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install
      - echo "******** Uploading to S3 ********"
artifacts:
  files:
    - source: site/target/mycompany.war
    - destination: site/target/mycompany.war
    - source: admin/target/admin.war
    - destination: admin/target/admin.war
  discard-paths: yes
